### ISSUE TITLE
nil pointer dereference with cumulus containers

### ISSUE THREAD

**Issue by rwxd** [srl-labs/containerlab#1054]
Hi, 

we are trying to run containerlab on a [baremetal from equinix](https://metal.equinix.com/product/servers/).

When we are trying to start a cumulus container, we get the following error:

```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x205c226]

goroutine 70 [running]:
github.com/weaveworks/ignite/pkg/apis/ignite.(*VM).SetKernel(...)
	github.com/weaveworks/ignite@v0.10.0/pkg/apis/ignite/helpers.go:18
github.com/srl-labs/containerlab/runtime/ignite.(*IgniteRuntime).StartContainer(0xc0004ffe90, {0x33121b0, 0xc00051a580}, {0x0?, 0x0?}, 0xc000a9c000)
	github.com/srl-labs/containerlab/runtime/ignite/ignite.go:178 +0x2a6
github.com/srl-labs/containerlab/nodes/cvx.(*cvx).Deploy(0xc0009badc0, {0x33121b0, 0xc00051a580})
	github.com/srl-labs/containerlab/nodes/cvx/cvx.go:82 +0x76
github.com/srl-labs/containerlab/clab.(*CLab).scheduleNodes.func1(0x0?, 0xc0000bd4a0, 0x0?, {0x3316a88, 0xc0009bf8b0})
	github.com/srl-labs/containerlab/clab/clab.go:308 +0x3e7
created by github.com/srl-labs/containerlab/clab.(*CLab).scheduleNodes
	github.com/srl-labs/containerlab/clab/clab.go:339 +0x145
```

We have installed kvm and successfully ran ignite vms.

## Trace

```bash
root@cmls:~/clabs/labs/cvx03# uname -a
Linux cmls 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
```

```bash
level=info msg="Containerlab v0.32.1 started"
level=debug msg="envN runtime var value is "
level=debug msg="Running runtime.Init with params &{Timeout:2m0s GracefulShutdown:false Debug:false KeepMgmtNet:false} and &{Network: Bridge: IPv4Subnet: IPv4Gw: IPv6Subnet: IPv6Gw: MTU: ExternalAccess:<nil>}"
level=debug msg="Runtime: Docker"
level=debug msg="detected docker network mtu value - 1500"
level=debug msg="initialized a runtime with params &{config:{Timeout:120000000000 GracefulShutdown:false Debug:false KeepMgmtNet:false} Client:0xc00021a480 mgmt:0xc00021a300}"
level=debug msg="template variables: <nil>"
level=debug msg="topology:\nname: ctd # Cumulus Linux Test Drive\n\ntopology:\n  nodes:\n    leaf01:\n      kind: cvx\n      image: networkop/cx:4.3.0\n\n    leaf02:\n      kind: cvx\n      image: networkop/cx:4.4.0\n\n    spine01:\n      kind: cvx\n      image: networkop/cx:5.1.0\n\n    server01:\n      kind: linux\n      image: networkop/host:ifreload\n      binds:\n        - server01/interfaces:/etc/network/interfaces\n\n    server02:\n      kind: linux\n      image: networkop/host:ifreload\n      binds:\n        - server02/interfaces:/etc/network/interfaces\n\n  links:\n    - endpoints: [\"leaf01:swp1\", \"server01:eth1\"]\n    - endpoints: [\"leaf01:swp2\", \"server02:eth1\"]\n    - endpoints: [\"leaf02:swp1\", \"server01:eth2\"]\n    - endpoints: [\"leaf02:swp2\", \"server02:eth2\"]\n\n    - endpoints: [\"leaf01:swp49\", \"leaf02:swp49\"]\n    - endpoints: [\"leaf01:swp50\", \"leaf02:swp50\"]\n\n    - endpoints: [\"spine01:swp1\", \"leaf01:swp51\"]\n    - endpoints: [\"spine01:swp2\", \"leaf02:swp51\"]\n\n"
level=debug msg="method initMgmtNetwork was called mgmt params &{Network: Bridge:br-239f23dd7eff IPv4Subnet: IPv4Gw: IPv6Subnet: IPv6Gw: MTU:1500 ExternalAccess:<nil>}"
level=debug msg="New mgmt params are &{Network:clab Bridge:br-239f23dd7eff IPv4Subnet:172.20.20.0/24 IPv4Gw: IPv6Subnet:2001:172:20:20::/64 IPv6Gw: MTU:1500 ExternalAccess:0xc000125a7a}"
level=info msg="Parsing & checking topology file: lab-start.clab.yml"
level=trace msg="Populating providers..."
level=trace msg="Initializing the GenericStorage provider..."
level=trace msg="Initializing the Client provider..."
level=trace msg="Initializing the Docker runtime provider..."
level=trace msg="Initializing the Docker network provider..."
level=trace msg="Populating providers..."
level=trace msg="Initializing the Docker runtime provider..."
level=trace msg="Initializing the Docker network provider..."
level=trace msg="Client.New; GVK: ignite.weave.works/__internal, Kind=VM"
level=debug msg="Runtime: Docker"
level=debug msg="node config: &{ShortName:leaf01 LongName:clab-ctd-leaf01 Fqdn:leaf01.ctd.io LabDir:/root/clabs/labs/cvx03/clab-ctd/leaf01 Index:0 Group: Kind:cvx StartupConfig: StartupDelay:0 EnforceStartupConfig:false ResStartupConfig: Config:<nil> ResConfig: NodeType: Position: License: Image:networkop/cx:4.3.0 Sysctls:map[] User: Entrypoint: Cmd: Exec:[] Env:map[] Binds:[] PortBindings:map[] PortSet:map[] NetworkMode: MgmtNet: MgmtIntf: MgmtIPv4Address: MgmtIPv4PrefixLength:0 MgmtIPv6Address: MgmtIPv6PrefixLength:0 MgmtIPv4Gateway: MgmtIPv6Gateway: MacAddress: ContainerID: TLSCert: TLSKey: TLSAnchor: NSPath: Publish:[] ExtraHosts:[] Labels:map[] Endpoints:[] SANs:[] Sandbox: Kernel: Runtime: CPU:0 CPUSet: Memory: HostRequirements:{SSE3:false VirtRequired:false} DeploymentStatus: Extras:<nil> WaitFor:[]}"
level=debug msg="node config: &{ShortName:leaf02 LongName:clab-ctd-leaf02 Fqdn:leaf02.ctd.io LabDir:/root/clabs/labs/cvx03/clab-ctd/leaf02 Index:1 Group: Kind:cvx StartupConfig: StartupDelay:0 EnforceStartupConfig:false ResStartupConfig: Config:<nil> ResConfig: NodeType: Position: License: Image:networkop/cx:4.4.0 Sysctls:map[] User: Entrypoint: Cmd: Exec:[] Env:map[] Binds:[] PortBindings:map[] PortSet:map[] NetworkMode: MgmtNet: MgmtIntf: MgmtIPv4Address: MgmtIPv4PrefixLength:0 MgmtIPv6Address: MgmtIPv6PrefixLength:0 MgmtIPv4Gateway: MgmtIPv6Gateway: MacAddress: ContainerID: TLSCert: TLSKey: TLSAnchor: NSPath: Publish:[] ExtraHosts:[] Labels:map[] Endpoints:[] SANs:[] Sandbox: Kernel: Runtime: CPU:0 CPUSet: Memory: HostRequirements:{SSE3:false VirtRequired:false} DeploymentStatus: Extras:<nil> WaitFor:[]}"
level=debug msg="node config: &{ShortName:server01 LongName:clab-ctd-server01 Fqdn:server01.ctd.io LabDir:/root/clabs/labs/cvx03/clab-ctd/server01 Index:2 Group: Kind:linux StartupConfig: StartupDelay:0 EnforceStartupConfig:false ResStartupConfig: Config:<nil> ResConfig: NodeType: Position: License: Image:networkop/host:ifreload Sysctls:map[] User: Entrypoint: Cmd: Exec:[] Env:map[] Binds:[] PortBindings:map[] PortSet:map[] NetworkMode: MgmtNet: MgmtIntf: MgmtIPv4Address: MgmtIPv4PrefixLength:0 MgmtIPv6Address: MgmtIPv6PrefixLength:0 MgmtIPv4Gateway: MgmtIPv6Gateway: MacAddress: ContainerID: TLSCert: TLSKey: TLSAnchor: NSPath: Publish:[] ExtraHosts:[] Labels:map[] Endpoints:[] SANs:[] Sandbox: Kernel: Runtime: CPU:0 CPUSet: Memory: HostRequirements:{SSE3:false VirtRequired:false} DeploymentStatus: Extras:<nil> WaitFor:[]}"
level=debug msg="node config: &{ShortName:server02 LongName:clab-ctd-server02 Fqdn:server02.ctd.io LabDir:/root/clabs/labs/cvx03/clab-ctd/server02 Index:3 Group: Kind:linux StartupConfig: StartupDelay:0 EnforceStartupConfig:false ResStartupConfig: Config:<nil> ResConfig: NodeType: Position: License: Image:networkop/host:ifreload Sysctls:map[] User: Entrypoint: Cmd: Exec:[] Env:map[] Binds:[] PortBindings:map[] PortSet:map[] NetworkMode: MgmtNet: MgmtIntf: MgmtIPv4Address: MgmtIPv4PrefixLength:0 MgmtIPv6Address: MgmtIPv6PrefixLength:0 MgmtIPv4Gateway: MgmtIPv6Gateway: MacAddress: ContainerID: TLSCert: TLSKey: TLSAnchor: NSPath: Publish:[] ExtraHosts:[] Labels:map[] Endpoints:[] SANs:[] Sandbox: Kernel: Runtime: CPU:0 CPUSet: Memory: HostRequirements:{SSE3:false VirtRequired:false} DeploymentStatus: Extras:<nil> WaitFor:[]}"
level=debug msg="node config: &{ShortName:spine01 LongName:clab-ctd-spine01 Fqdn:spine01.ctd.io LabDir:/root/clabs/labs/cvx03/clab-ctd/spine01 Index:4 Group: Kind:cvx StartupConfig: StartupDelay:0 EnforceStartupConfig:false ResStartupConfig: Config:<nil> ResConfig: NodeType: Position: License: Image:networkop/cx:5.1.0 Sysctls:map[] User: Entrypoint: Cmd: Exec:[] Env:map[] Binds:[] PortBindings:map[] PortSet:map[] NetworkMode: MgmtNet: MgmtIntf: MgmtIPv4Address: MgmtIPv4PrefixLength:0 MgmtIPv6Address: MgmtIPv6PrefixLength:0 MgmtIPv4Gateway: MgmtIPv6Gateway: MacAddress: ContainerID: TLSCert: TLSKey: TLSAnchor: NSPath: Publish:[] ExtraHosts:[] Labels:map[] Endpoints:[] SANs:[] Sandbox: Kernel: Runtime: CPU:0 CPUSet: Memory: HostRequirements:{SSE3:false VirtRequired:false} DeploymentStatus: Extras:<nil> WaitFor:[]}"
level=debug msg="lab Conf: &{Name:ctd Prefix:0xc0007961f0 Mgmt:0xc00021a300 Topology:0xc000acf200}"
level=debug msg="Env: CLAB_VERSION_CHECK="
level=trace msg="Client.FindAll; GVK: ignite.weave.works/__internal, Kind=VM"
level=trace msg="index: counted 0 VM object(s)"
level=trace msg="cache: hit when listing: ignite.weave.works/__internal, Kind=VM"
level=trace msg="index: listing ignite.weave.works/__internal, Kind=VM objects, meta: false"
level=debug msg="Ensuring image networkop/cx:4.4.0 exists, or importing it..."
level=trace msg="Client.Find; GVK: ignite.weave.works/__internal, Kind=Image"
level=trace msg="index: counted 0 Image object(s)"
level=trace msg="cache: miss when listing: ignite.weave.works/__internal, Kind=Image"
level=trace msg="cache: Get Image with UID \"0d130e45d7641aa5\""
level=trace msg="index: cache miss for Image with UID \"0d130e45d7641aa5\""
level=trace msg="index: storing Image object with UID \"networkop/cx:4.4.0\", meta: false"
level=debug msg="Found image with UID 0d130e45d7641aa5"
level=debug msg="Looking up networkop/host:ifreload Docker image"
level=debug msg="Image networkop/host:ifreload present, skip pulling"
level=debug msg="Ensuring image networkop/cx:5.1.0 exists, or importing it..."
level=trace msg="Client.Find; GVK: ignite.weave.works/__internal, Kind=Image"
level=trace msg="index: counted 1 Image object(s)"
level=trace msg="cache: miss when listing: ignite.weave.works/__internal, Kind=Image"
level=trace msg="cache: Get Image with UID \"1b2c135de38e483d\""
level=trace msg="index: cache miss for Image with UID \"1b2c135de38e483d\""
level=trace msg="index: storing Image object with UID \"networkop/cx:5.1.0\", meta: false"
level=debug msg="Found image with UID 1b2c135de38e483d"
level=debug msg="Ensuring image networkop/cx:4.3.0 exists, or importing it..."
level=trace msg="Client.Find; GVK: ignite.weave.works/__internal, Kind=Image"
level=trace msg="index: counted 2 Image object(s)"
level=trace msg="cache: miss when listing: ignite.weave.works/__internal, Kind=Image"
level=trace msg="cache: Get Image with UID \"4fef7efa02a9b55c\""
level=trace msg="index: cache miss for Image with UID \"4fef7efa02a9b55c\""
level=trace msg="index: storing Image object with UID \"networkop/cx:4.3.0\", meta: false"
level=debug msg="Found image with UID 4fef7efa02a9b55c"
level=debug msg="Ensuring image networkop/kernel:4.19 exists, or importing it..."
level=trace msg="Client.Find; GVK: ignite.weave.works/__internal, Kind=Image"
level=trace msg="index: counted 3 Image object(s)"
level=trace msg="cache: miss when listing: ignite.weave.works/__internal, Kind=Image"
level=trace msg="cache: Get Image with UID \"0ff8f0ee07e4fbbf\""
level=trace msg="index: cache miss for Image with UID \"0ff8f0ee07e4fbbf\""
level=trace msg="index: storing Image object with UID \"networkop/kernel:4.19\", meta: false"
level=debug msg="Found image with UID 0ff8f0ee07e4fbbf"
level=debug msg="Ensuring image networkop/ignite:dev exists, or importing it..."
level=trace msg="Client.Find; GVK: ignite.weave.works/__internal, Kind=Image"
level=trace msg="index: counted 4 Image object(s)"
level=trace msg="cache: miss when listing: ignite.weave.works/__internal, Kind=Image"
level=trace msg="cache: Get Image with UID \"4c4de817666ef0ba\""
level=trace msg="index: cache miss for Image with UID \"4c4de817666ef0ba\""
level=trace msg="index: storing Image object with UID \"networkop/ignite:dev\", meta: false"
level=debug msg="Found image with UID 4c4de817666ef0ba"
level=debug msg="Number of vcpu: 16"
level=info msg="Creating lab directory: /root/clabs/labs/cvx03/clab-ctd"
level=debug msg="/root/.ssh/authorized_keys found, adding the public keys it contains"
level=debug msg="found public key files [\"/root/.ssh/authorized_keys\"]"
level=debug msg="Checking if docker network \"clab\" exists"
level=debug msg="Network \"clab\" does not exist"
level=info msg="Creating docker network: Name=\"clab\", IPv4Subnet=\"172.20.20.0/24\", IPv6Subnet=\"2001:172:20:20::/64\", MTU=\"1500\""
level=debug msg="bridge \"br-239f23dd7eff\" has ipv4 adrr of \"\" and ipv6 addr of \"\""
level=debug msg="Docker network \"clab\", bridge name \"br-239f23dd7eff\""
level=debug msg="Disable RPF check on the docker host"
level=debug msg="Enable LLDP on the linux bridge br-239f23dd7eff"
level=debug msg="Disabling TX checksum offloading for the br-239f23dd7eff bridge interface..."
level=debug msg="Installing iptables rules for bridge \"br-239f23dd7eff\""
level=debug msg="Dependencies:\nleaf02 -> [  ]\nserver01 -> [  ]\nserver02 -> [  ]\nspine01 -> [  ]\nleaf01 -> [  ]"
level=debug msg="- cycle check round 1 - \nleaf02 <- [  ]\nserver01 <- [  ]\nserver02 <- [  ]\nspine01 <- [  ]\nleaf01 <- [  ]"
level=debug msg="node creation graph is successfully validated as being acyclic"
level=debug msg="Worker 0 received node: &{ShortName:spine01 LongName:clab-ctd-spine01 Fqdn:spine01.ctd.io LabDir:/root/clabs/labs/cvx03/clab-ctd/spine01 Index:4 Group: Kind:cvx StartupConfig: StartupDelay:0 EnforceStartupConfig:false ResStartupConfig: Config:0xc0006fac28 ResConfig: NodeType: Position: License: Image:networkop/cx:5.1.0 Sysctls:map[] User: Entrypoint: Cmd: Exec:[] Env:map[CLAB_INTFS:2 CLAB_LABEL_CLAB_NODE_GROUP: CLAB_LABEL_CLAB_NODE_KIND:cvx CLAB_LABEL_CLAB_NODE_LAB_DIR:/root/clabs/labs/cvx03/clab-ctd/spine01 CLAB_LABEL_CLAB_NODE_NAME:spine01 CLAB_LABEL_CLAB_NODE_TYPE: CLAB_LABEL_CLAB_TOPO_FILE:/root/clabs/labs/cvx03/lab-start.clab.yml CLAB_LABEL_CONTAINERLAB:ctd] Binds:[] PortBindings:map[] PortSet:map[] NetworkMode: MgmtNet: MgmtIntf: MgmtIPv4Address: MgmtIPv4PrefixLength:0 MgmtIPv6Address: MgmtIPv6PrefixLength:0 MgmtIPv4Gateway: MgmtIPv6Gateway: MacAddress: ContainerID: TLSCert: TLSKey: TLSAnchor: NSPath: Publish:[] ExtraHosts:[] Labels:map[clab-mgmt-net-bridge:br-239f23dd7eff clab-node-group: clab-node-kind:cvx clab-node-lab-dir:/root/clabs/labs/cvx03/clab-ctd/spine01 clab-node-name:spine01 clab-node-type: clab-topo-file:/root/clabs/labs/cvx03/lab-start.clab.yml containerlab:ctd] Endpoints:[{Node:0xc000a9d500 EndpointName:swp1 MAC:aa:c1:ab:1f:07:c5} {Node:0xc000a9d500 EndpointName:swp2 MAC:aa:c1:ab:d1:81:44}] SANs:[] Sandbox:networkop/ignite:dev Kernel:docker.io/networkop/kernel:4.19 Runtime: CPU:0 CPUSet: Memory:768MB HostRequirements:{SSE3:false VirtRequired:false} DeploymentStatus: Extras:<nil> WaitFor:[]}"
level=debug msg="Worker 4 received node: &{ShortName:leaf02 LongName:clab-ctd-leaf02 Fqdn:leaf02.ctd.io LabDir:/root/clabs/labs/cvx03/clab-ctd/leaf02 Index:1 Group: Kind:cvx StartupConfig: StartupDelay:0 EnforceStartupConfig:false ResStartupConfig: Config:0xc0006faac0 ResConfig: NodeType: Position: License: Image:networkop/cx:4.4.0 Sysctls:map[] User: Entrypoint: Cmd: Exec:[] Env:map[CLAB_INTFS:5 CLAB_LABEL_CLAB_NODE_GROUP: CLAB_LABEL_CLAB_NODE_KIND:cvx CLAB_LABEL_CLAB_NODE_LAB_DIR:/root/clabs/labs/cvx03/clab-ctd/leaf02 CLAB_LABEL_CLAB_NODE_NAME:leaf02 CLAB_LABEL_CLAB_NODE_TYPE: CLAB_LABEL_CLAB_TOPO_FILE:/root/clabs/labs/cvx03/lab-start.clab.yml CLAB_LABEL_CONTAINERLAB:ctd] Binds:[] PortBindings:map[] PortSet:map[] NetworkMode: MgmtNet: MgmtIntf: MgmtIPv4Address: MgmtIPv4PrefixLength:0 MgmtIPv6Address: MgmtIPv6PrefixLength:0 MgmtIPv4Gateway: MgmtIPv6Gateway: MacAddress: ContainerID: TLSCert: TLSKey: TLSAnchor: NSPath: Publish:[] ExtraHosts:[] Labels:map[clab-mgmt-net-bridge:br-239f23dd7eff clab-node-group: clab-node-kind:cvx clab-node-lab-dir:/root/clabs/labs/cvx03/clab-ctd/leaf02 clab-node-name:leaf02 clab-node-type: clab-topo-file:/root/clabs/labs/cvx03/lab-start.clab.yml containerlab:ctd] Endpoints:[{Node:0xc000a9c000 EndpointName:swp1 MAC:aa:c1:ab:0c:30:f0} {Node:0xc000a9c000 EndpointName:swp2 MAC:aa:c1:ab:c7:5a:a8} {Node:0xc000a9c000 EndpointName:swp49 MAC:aa:c1:ab:4b:13:03} {Node:0xc000a9c000 EndpointName:swp50 MAC:aa:c1:ab:4a:b4:54} {Node:0xc000a9c000 EndpointName:swp51 MAC:aa:c1:ab:8c:00:c7}] SANs:[] Sandbox:networkop/ignite:dev Kernel:docker.io/networkop/kernel:4.19 Runtime: CPU:0 CPUSet: Memory:768MB HostRequirements:{SSE3:false VirtRequired:false} DeploymentStatus: Extras:<nil> WaitFor:[]}"
level=debug msg="creating links..."
level=debug msg="Worker 1 received node: &{ShortName:leaf01 LongName:clab-ctd-leaf01 Fqdn:leaf01.ctd.io LabDir:/root/clabs/labs/cvx03/clab-ctd/leaf01 Index:0 Group: Kind:cvx StartupConfig: StartupDelay:0 EnforceStartupConfig:false ResStartupConfig: Config:0xc0006faa48 ResConfig: NodeType: Position: License: Image:networkop/cx:4.3.0 Sysctls:map[] User: Entrypoint: Cmd: Exec:[] Env:map[CLAB_INTFS:5 CLAB_LABEL_CLAB_NODE_GROUP: CLAB_LABEL_CLAB_NODE_KIND:cvx CLAB_LABEL_CLAB_NODE_LAB_DIR:/root/clabs/labs/cvx03/clab-ctd/leaf01 CLAB_LABEL_CLAB_NODE_NAME:leaf01 CLAB_LABEL_CLAB_NODE_TYPE: CLAB_LABEL_CLAB_TOPO_FILE:/root/clabs/labs/cvx03/lab-start.clab.yml CLAB_LABEL_CONTAINERLAB:ctd] Binds:[] PortBindings:map[] PortSet:map[] NetworkMode: MgmtNet: MgmtIntf: MgmtIPv4Address: MgmtIPv4PrefixLength:0 MgmtIPv6Address: MgmtIPv6PrefixLength:0 MgmtIPv4Gateway: MgmtIPv6Gateway: MacAddress: ContainerID: TLSCert: TLSKey: TLSAnchor: NSPath: Publish:[] ExtraHosts:[] Labels:map[clab-mgmt-net-bridge:br-239f23dd7eff clab-node-group: clab-node-kind:cvx clab-node-lab-dir:/root/clabs/labs/cvx03/clab-ctd/leaf01 clab-node-name:leaf01 clab-node-type: clab-topo-file:/root/clabs/labs/cvx03/lab-start.clab.yml containerlab:ctd] Endpoints:[{Node:0xc0001d6700 EndpointName:swp1 MAC:aa:c1:ab:26:60:c4} {Node:0xc0001d6700 EndpointName:swp2 MAC:aa:c1:ab:5b:06:94} {Node:0xc0001d6700 EndpointName:swp49 MAC:aa:c1:ab:23:e4:f3} {Node:0xc0001d6700 EndpointName:swp50 MAC:aa:c1:ab:5b:cf:0a} {Node:0xc0001d6700 EndpointName:swp51 MAC:aa:c1:ab:4a:cf:3d}] SANs:[] Sandbox:networkop/ignite:dev Kernel:docker.io/networkop/kernel:4.19 Runtime: CPU:0 CPUSet: Memory:512MB HostRequirements:{SSE3:false VirtRequired:false} DeploymentStatus: Extras:<nil> WaitFor:[]}"
level=debug msg="Worker 3 received node: &{ShortName:server02 LongName:clab-ctd-server02 Fqdn:server02.ctd.io LabDir:/root/clabs/labs/cvx03/clab-ctd/server02 Index:3 Group: Kind:linux StartupConfig: StartupDelay:0 EnforceStartupConfig:false ResStartupConfig: Config:0xc0006fabb0 ResConfig: NodeType: Position: License: Image:networkop/host:ifreload Sysctls:map[net.ipv6.conf.all.disable_ipv6:0] User: Entrypoint: Cmd: Exec:[] Env:map[CLAB_INTFS:2 CLAB_LABEL_CLAB_NODE_GROUP: CLAB_LABEL_CLAB_NODE_KIND:linux CLAB_LABEL_CLAB_NODE_LAB_DIR:/root/clabs/labs/cvx03/clab-ctd/server02 CLAB_LABEL_CLAB_NODE_NAME:server02 CLAB_LABEL_CLAB_NODE_TYPE: CLAB_LABEL_CLAB_TOPO_FILE:/root/clabs/labs/cvx03/lab-start.clab.yml CLAB_LABEL_CONTAINERLAB:ctd] Binds:[/root/clabs/labs/cvx03/server02/interfaces:/etc/network/interfaces] PortBindings:map[] PortSet:map[] NetworkMode: MgmtNet: MgmtIntf: MgmtIPv4Address: MgmtIPv4PrefixLength:0 MgmtIPv6Address: MgmtIPv6PrefixLength:0 MgmtIPv4Gateway: MgmtIPv6Gateway: MacAddress: ContainerID: TLSCert: TLSKey: TLSAnchor: NSPath: Publish:[] ExtraHosts:[] Labels:map[clab-mgmt-net-bridge:br-239f23dd7eff clab-node-group: clab-node-kind:linux clab-node-lab-dir:/root/clabs/labs/cvx03/clab-ctd/server02 clab-node-name:server02 clab-node-type: clab-topo-file:/root/clabs/labs/cvx03/lab-start.clab.yml containerlab:ctd] Endpoints:[{Node:0xc000a9ce00 EndpointName:eth1 MAC:aa:c1:ab:7e:da:71} {Node:0xc000a9ce00 EndpointName:eth2 MAC:aa:c1:ab:3c:54:0d}] SANs:[] Sandbox: Kernel: Runtime: CPU:0 CPUSet: Memory: HostRequirements:{SSE3:false VirtRequired:false} DeploymentStatus: Extras:<nil> WaitFor:[]}"
level=info msg="Creating container: \"server02\""
level=debug msg="Ensuring kernel networkop/kernel:4.19 exists, or importing it..."
level=trace msg="Client.Find; GVK: ignite.weave.works/__internal, Kind=Kernel"
level=debug msg="Ensuring kernel networkop/kernel:4.19 exists, or importing it..."
level=trace msg="index: counted 0 Kernel object(s)"
level=trace msg="Client.Find; GVK: ignite.weave.works/__internal, Kind=Kernel"
level=trace msg="cache: miss when listing: ignite.weave.works/__internal, Kind=Kernel"
level=trace msg="index: counted 0 Kernel object(s)"
level=trace msg="cache: miss when listing: ignite.weave.works/__internal, Kind=Kernel"
level=debug msg="Worker 2 received node: &{ShortName:server01 LongName:clab-ctd-server01 Fqdn:server01.ctd.io LabDir:/root/clabs/labs/cvx03/clab-ctd/server01 Index:2 Group: Kind:linux StartupConfig: StartupDelay:0 EnforceStartupConfig:false ResStartupConfig: Config:0xc0006fab38 ResConfig: NodeType: Position: License: Image:networkop/host:ifreload Sysctls:map[net.ipv6.conf.all.disable_ipv6:0] User: Entrypoint: Cmd: Exec:[] Env:map[CLAB_INTFS:2 CLAB_LABEL_CLAB_NODE_GROUP: CLAB_LABEL_CLAB_NODE_KIND:linux CLAB_LABEL_CLAB_NODE_LAB_DIR:/root/clabs/labs/cvx03/clab-ctd/server01 CLAB_LABEL_CLAB_NODE_NAME:server01 CLAB_LABEL_CLAB_NODE_TYPE: CLAB_LABEL_CLAB_TOPO_FILE:/root/clabs/labs/cvx03/lab-start.clab.yml CLAB_LABEL_CONTAINERLAB:ctd] Binds:[/root/clabs/labs/cvx03/server01/interfaces:/etc/network/interfaces] PortBindings:map[] PortSet:map[] NetworkMode: MgmtNet: MgmtIntf: MgmtIPv4Address: MgmtIPv4PrefixLength:0 MgmtIPv6Address: MgmtIPv6PrefixLength:0 MgmtIPv4Gateway: MgmtIPv6Gateway: MacAddress: ContainerID: TLSCert: TLSKey: TLSAnchor: NSPath: Publish:[] ExtraHosts:[] Labels:map[clab-mgmt-net-bridge:br-239f23dd7eff clab-node-group: clab-node-kind:linux clab-node-lab-dir:/root/clabs/labs/cvx03/clab-ctd/server01 clab-node-name:server01 clab-node-type: clab-topo-file:/root/clabs/labs/cvx03/lab-start.clab.yml containerlab:ctd] Endpoints:[{Node:0xc000a9c700 EndpointName:eth1 MAC:aa:c1:ab:fc:2f:36} {Node:0xc000a9c700 EndpointName:eth2 MAC:aa:c1:ab:ba:85:44}] SANs:[] Sandbox: Kernel: Runtime: CPU:0 CPUSet: Memory: HostRequirements:{SSE3:false VirtRequired:false} DeploymentStatus: Extras:<nil> WaitFor:[]}"
level=info msg="Creating container: \"server01\""
level=debug msg="Ensuring kernel networkop/kernel:4.19 exists, or importing it..."
level=trace msg="Client.Find; GVK: ignite.weave.works/__internal, Kind=Kernel"
level=trace msg="index: counted 0 Kernel object(s)"
level=trace msg="cache: miss when listing: ignite.weave.works/__internal, Kind=Kernel"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x205c226]

goroutine 70 [running]:
github.com/weaveworks/ignite/pkg/apis/ignite.(*VM).SetKernel(...)
	github.com/weaveworks/ignite@v0.10.0/pkg/apis/ignite/helpers.go:18
github.com/srl-labs/containerlab/runtime/ignite.(*IgniteRuntime).StartContainer(0xc0004ffe90, {0x33121b0, 0xc00051a580}, {0x0?, 0x0?}, 0xc000a9c000)
	github.com/srl-labs/containerlab/runtime/ignite/ignite.go:178 +0x2a6
github.com/srl-labs/containerlab/nodes/cvx.(*cvx).Deploy(0xc0009badc0, {0x33121b0, 0xc00051a580})
	github.com/srl-labs/containerlab/nodes/cvx/cvx.go:82 +0x76
github.com/srl-labs/containerlab/clab.(*CLab).scheduleNodes.func1(0x0?, 0xc0000bd4a0, 0x0?, {0x3316a88, 0xc0009bf8b0})
	github.com/srl-labs/containerlab/clab/clab.go:308 +0x3e7
created by github.com/srl-labs/containerlab/clab.(*CLab).scheduleNodes
	github.com/srl-labs/containerlab/clab/clab.go:339 +0x145
```

## Lab Configuration

<https://github.com/hellt/clabs/blob/main/labs/cvx03/lab-start.clab.yml>

```yaml
name: ctd # Cumulus Linux Test Drive

topology:
  nodes:
    leaf01:
      kind: cvx
      image: networkop/cx:4.3.0

    leaf02:
      kind: cvx
      image: networkop/cx:4.4.0

    spine01:
      kind: cvx
      image: networkop/cx:5.1.0

    server01:
      kind: linux
      image: networkop/host:ifreload
      binds:
        - server01/interfaces:/etc/network/interfaces

    server02:
      kind: linux
      image: networkop/host:ifreload
      binds:
        - server02/interfaces:/etc/network/interfaces

  links:
    - endpoints: ["leaf01:swp1", "server01:eth1"]
    - endpoints: ["leaf01:swp2", "server02:eth1"]
    - endpoints: ["leaf02:swp1", "server01:eth2"]
    - endpoints: ["leaf02:swp2", "server02:eth2"]

    - endpoints: ["leaf01:swp49", "leaf02:swp49"]
    - endpoints: ["leaf01:swp50", "leaf02:swp50"]

    - endpoints: ["spine01:swp1", "leaf01:swp51"]
    - endpoints: ["spine01:swp2", "leaf02:swp51"]
```

**Comment by hellt** [comment]
Hi there
unfortunately, ignite-based runtime is not possible anymore with recent containerlab versions.
It was recently discovered (#1039) that ignite runtime depends on an old version of a particular package that has been updated in our repo to support other packages.

You either need to specify a docker runtime with ignite nodes as indicated in the cvx docs, or (if ignite runtime is needed) you have to use an older version of containerlab, for example 0.27.1
