### ISSUE TITLE
Index out of range error in v0.34.0 when using ext-container

### ISSUE THREAD

**Issue by oshothebig** [srl-labs/containerlab#1152]
Index out of range error happens in v0.34.0 when using ext-container. The error doesn't happen in v0.33.0.

The following is a topology file that can cause the error.

```yaml
name: extcont

topology:
  nodes:
    external1:
      kind: ext-container
    external2:
      kind: ext-container
  links:
  - endpoints: ["external1:eth1", "external2:eth1"]
```

Create `external1` and `external2` containers and run `sudo clab deploy`, then we'll see the issue when using v0.34.0.

```
$ docker run -d --name external1 -t ghcr.io/nicolaka/netshoot
8ab771a11317977a78f1e2842a566e0a9eb22f488bb5e49028da6463a7477f60
$ docker run -d --name external2 -t ghcr.io/nicolaka/netshoot
ca35e14b18d72852ff0b334a7ea88745bdb4f078a4b8f8198554a076903ab35a
$ sudo clab deploy
INFO[0000] Containerlab v0.34.0 started
INFO[0000] Parsing & checking topology file: extcont.clab.yaml
INFO[0000] Creating lab directory: /home/ubuntu/extcont/clab-extcont
INFO[0001] Creating virtual wire: external1:eth1 <--> external2:eth1
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/srl-labs/containerlab/nodes.(*DefaultNode).UpdateConfigWithRuntimeInfo(0x4000797a00, {0x2cdbe30?, 0x4000797a80?})
	github.com/srl-labs/containerlab/nodes/default_node.go:144 +0x190
github.com/srl-labs/containerlab/cmd.deployFn(0x4316dc0?, {0x26cb2ef?, 0x0?, 0x0?})
	github.com/srl-labs/containerlab/cmd/deploy.go:206 +0xc40
github.com/spf13/cobra.(*Command).execute(0x4316dc0, {0x4558a88, 0x0, 0x0})
	github.com/spf13/cobra@v1.6.1/command.go:916 +0x60c
github.com/spf13/cobra.(*Command).ExecuteC(0x4315100)
	github.com/spf13/cobra@v1.6.1/command.go:1044 +0x368
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.1/command.go:968
github.com/srl-labs/containerlab/cmd.Execute()
	github.com/srl-labs/containerlab/cmd/root.go:46 +0x2c
main.main()
	github.com/srl-labs/containerlab/main.go:10 +0x20
```

In v0.33.0, `sudo clab deploy` succeeds.

```
$ docker run -d --name external1 -t ghcr.io/nicolaka/netshoot
389fde9af9b3274716864bf347890d20a8c8968b26ef09c3695c6ca697d2efdb
$ docker run -d --name external2 -t ghcr.io/nicolaka/netshoot
809577b67e5320fc7fe4f7a07f470fff72894112da309c80019fb833afb47f8e
$ sudo clab deploy
INFO[0000] Containerlab v0.33.0 started
INFO[0000] Parsing & checking topology file: extcont.clab.yaml
INFO[0000] Creating lab directory: /home/ubuntu/extcont/clab-extcont
INFO[0000] Creating docker network: Name="clab", IPv4Subnet="172.20.20.0/24", IPv6Subnet="2001:172:20:20::/64", MTU="1500"
INFO[0001] Creating virtual wire: external1:eth1 <--> external2:eth1
INFO[0001] Adding containerlab host entries to /etc/hosts file
INFO[0001] 🎉 New containerlab version 0.34.0 is available! Release notes: https://containerlab.dev/rn/0.34/
Run 'containerlab version upgrade' to upgrade or go check other installation options at https://containerlab.dev/install/
+---+------+--------------+-------+------+-------+--------------+--------------+
| # | Name | Container ID | Image | Kind | State | IPv4 Address | IPv6 Address |
+---+------+--------------+-------+------+-------+--------------+--------------+
+---+------+--------------+-------+------+-------+--------------+--------------+
```

I think the cause is `GetContainers()` implementation for `ext_container.extcont`. In ext-container, the container name is normally unprefixed, and then `GetContainers()` returns an empty slice.

**Comment by oshothebig** [comment]
I'm trying to fix the issue at https://github.com/oshothebig/containerlab/tree/list-ext-container. I'd like to discuss how to fix it properly as my WIP branch includes duplications with `DefaultNode.UpdateConfigWithRuntimeInfo(ctx context.Context)`

https://github.com/srl-labs/containerlab/blob/3a206aa2e137b09c8853a9697487bcc81a675725/nodes/default_node.go#L135-L156

**Comment by hellt** [comment]
Hey @oshothebig 
Thanks for reporting this. We will have a look, something slipped after the refactoring done in 0.34. 
Given the holidays here it might take time for us to get to it

**Comment by steiler** [comment]
Hi @oshothebig take a look at #1154.
The OverwriteNode interface is used to "relay" calls issued in the default node back to the specific node implementation.

If there is no specific implementation, that will again fall back to the default node.

**Comment by oshothebig** [comment]
@steiler Thanks for letting me know OverwriteNode. I didn't know such mechanism. I'll take a look at #1154.

**Comment by hellt** [comment]
thanks all
#1154 has been merged and will be part of the next release

@oshothebig if you need it sooner, you can pull the beta 
```
docker run --rm -v $(pwd):/workspace ghcr.io/oras-project/oras:v0.12.0 pull ghcr.io/srl-labs/clab-oci:34a5e86a
```

**Comment by oshothebig** [comment]
Thanks for fixing the issue and sharing how to pull the beta.
