### ISSUE TITLE
vr-sros sendpartialconfig

### ISSUE THREAD

**Issue by steiler** [srl-labs/containerlab#1422]
having partial startup-config which is empty leads to a panic.
We should therefor catch that and avoid the call.

Or maybe allow that to happen in scrapli fix that in scrapli. 
```
panic: runtime error: slice bounds out of range [:-1]

goroutine 109 [running]:
github.com/scrapli/scrapligo/driver/generic.(*Driver).SendCommands(0xc0006a6ff0, {0x0?, 0x0, 0x0}, {0x0, 0x0, 0x0})
        github.com/scrapli/scrapligo@v1.1.8/driver/generic/sendcommands.go:22 +0x388
github.com/scrapli/scrapligo/driver/network.(*Driver).SendConfigs(0xc000887b60, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})
        github.com/scrapli/scrapligo@v1.1.8/driver/network/sendconfigs.go:37 +0xb8
github.com/scrapli/scrapligo/driver/network.(*Driver).SendConfigsFromFile(0xc000887b60?, {0xc0007e85f0?, 0xc000e1ede0?}, {0x0, 0x0, 0x0})
        github.com/scrapli/scrapligo@v1.1.8/driver/network/sendconfigs.go:51 +0x71
github.com/srl-labs/containerlab/nodes/vr_sros.(*vrSROS).applyPartialConfig(0xc000134050, {0x335c018, 0xc0011f73e0}, {0xc000e1ede0, 0xb}, {0x2d7fef5, 0xa}, {0x2d74a8a, 0x5}, {0x2d74a8a, ...}, ...)
        github.com/srl-labs/containerlab/nodes/vr_sros/vr-sros.go:243 +0x725
github.com/srl-labs/containerlab/nodes/vr_sros.(*vrSROS).PostDeploy(0xc000134050, {0x335bfa8, 0xc0000c1220}, 0x0?)
        github.com/srl-labs/containerlab/nodes/vr_sros/vr-sros.go:108 +0x1db
github.com/srl-labs/containerlab/cmd.deployFn.func2({0x3373fb0, 0xc000134050}, 0xc000738000?)
        github.com/srl-labs/containerlab/cmd/deploy.go:254 +0xdc
created by github.com/srl-labs/containerlab/cmd.deployFn
        github.com/srl-labs/containerlab/cmd/deploy.go:251 +0x189c
```

**Comment by steiler** [comment]
trying to fix in scrapli first. Otherwise we need a workaround
