### ISSUE TITLE
vSRX Unable to connect to qemu monitor

### ISSUE THREAD

**Issue by akielaries** [srl-labs/containerlab#1462]
From recent issues I had seen suggestions that resources could be an cause for this error when booting up vrnetlab containers but that doesn't seem to fix my issue. I am getting an error with QEMU that there is no overlay file being created from my source image, I ran into no issues with vMX and was even able to create a simple containerlab topology, but vSRX is giving me some issues. To my knowledge, all that is needed for the vSRX VM container to run is the .qcow2 image from https://support.juniper.net to be in the vsrx directory and type `make`, am I missing something?
```
2023-07-07 23:44:18,117: vrnetlab   DEBUG    Creating overlay disk image
qemu-img: /junos-vsrx3-x86-64-23.2R1.13-overlay.qcow2: Backing file specified without backing format
Detected format of qcow2.2023-07-07 23:44:18,124: vrnetlab   DEBUG    Starting vrnetlab VSRX
2023-07-07 23:44:18,124: vrnetlab   DEBUG    VMs: [<__main__.VSRX_vm object at 0x7fa2bd06fdd0>]
2023-07-07 23:44:18,125: vrnetlab   DEBUG    VM not started; starting!
2023-07-07 23:44:18,125: vrnetlab   INFO     Starting VSRX_vm
2023-07-07 23:44:18,125: vrnetlab   DEBUG    number of provisioned data plane interfaces is 1
2023-07-07 23:44:18,126: vrnetlab   DEBUG    waiting for provisioned interfaces to appear...
2023-07-07 23:44:23,126: vrnetlab   DEBUG    highest allocated interface id determined to be: 1...
2023-07-07 23:44:23,127: vrnetlab   DEBUG    interfaces provisioned, continuing...
2023-07-07 23:44:23,127: vrnetlab   DEBUG    qemu cmd: qemu-system-x86_64 -enable-kvm -display none -machine pc -monitor tcp:0.0.0.0:4000,server,nowait -m 8192 -serial telnet:0.0.0.0:5000,server,nowait -drive if=ide,file=/junos-vsrx3-x86-64-23.2R1.13-overlay.qcow2 -smp 2 -device pci-bridge,chassis_nr=1,id=pci.1 -device virtio-net-pci,netdev=p00,mac=0C:00:d4:8a:01:00 -netdev user,id=p00,net=10.0.0.0/24,tftp=/tftpboot,hostfwd=tcp::2022-10.0.0.15:22,hostfwd=udp::2161-10.0.0.15:161,hostfwd=tcp::2830-10.0.0.15:830,hostfwd=tcp::2080-10.0.0.15:80,hostfwd=tcp::2443-10.0.0.15:443 -device virtio-net-pci,netdev=p01,mac=0C:00:b9:9e:bc:01,bus=pci.1,addr=0x2 -netdev tap,id=p01,ifname=tap1,script=/etc/tc-tap-ifup,downscript=no
2023-07-07 23:44:23,154: vrnetlab   INFO     STDOUT:
2023-07-07 23:44:23,154: vrnetlab   INFO     STDERR: qemu-system-x86_64: -drive if=ide,file=/junos-vsrx3-x86-64-23.2R1.13-overlay.qcow2: Could not open '/junos-vsrx3-x86-64-23.2R1.13-overlay.qcow2': No such file or directory

2023-07-07 23:44:23,156: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 1)
2023-07-07 23:44:24,156: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 2)
2023-07-07 23:44:25,157: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 3)
2023-07-07 23:44:26,157: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 4)
2023-07-07 23:44:27,158: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 5)
...
2023-07-07 23:45:21,184: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 59)
2023-07-07 23:45:22,185: vrnetlab   INFO     Unable to connect to qemu monitor (port 4000), retrying in a second (attempt 60)
Traceback (most recent call last):
  File "/launch.py", line 145, in <module>
    vr.start()
  File "/vrnetlab.py", line 735, in start
    vm.work()
  File "/vrnetlab.py", line 666, in work
    self.check_qemu()
  File "/vrnetlab.py", line 680, in check_qemu
    self.start()
  File "/vrnetlab.py", line 193, in start
    raise QemuBroken(
vrnetlab.QemuBroken: Unable to connect to qemu monitor on port 4000
```

I am looking to add vJunosEvolved and vJunos-switch images for vrnetlab/containerlab and the process for getting these running in a VM is very similar (involving a single qcow2 image). Getting vSRX working would be a good starter point for these new images.

**Comment by hellt** [comment]
Hi @akielaries 
Are you using the latest hellt/vrnetlab when trying to build that? This issue rather belongs to that repo. Can you move it over? There are vSRX users who launched it just fine, we can add them to comments there.

I am closing this one here

**Comment by akielaries** [comment]
Ah yes, I should've brought this up in hellt/vrnetlab. I'll bring the issue over there, any help would be much appreciated
