### ISSUE TITLE
Host node panics if the distro doesn't have a lsb-release file

### ISSUE THREAD

**Issue by NovAti0n** [srl-labs/containerlab#2245]
I'm using Containerlab on a RPI running RPI OS. Debian doesn't have a `/etc/lsb-release` file by default, so when creating a host node, the function `getOSRelease()` crashes when running the regex since `/etc/os-release` doesn't have a `DISTRIB_DESCRIPTION` field. This causes line 80 to panic with an index out of bounds.

```
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
github.com/srl-labs/containerlab/nodes/host.getOSRelease()
        github.com/srl-labs/containerlab/nodes/host/host.go:80 +0xd8
github.com/srl-labs/containerlab/nodes/host.(*host).GetContainers(0x4000abf758?, {0x3481790?, 0x40007cc870?})
        github.com/srl-labs/containerlab/nodes/host/host.go:85 +0x1c
github.com/srl-labs/containerlab/clab.(*CLab).ListNodesContainersIgnoreNotFound(0x4?, {0x3481790, 0x40007cc870})
        github.com/srl-labs/containerlab/clab/clab.go:852 +0xb4
github.com/srl-labs/containerlab/clab.(*CLab).Destroy(0x40002f78c0, {0x3481790, 0x40007cc870}, 0x0, 0x0)
        github.com/srl-labs/containerlab/clab/clab.go:1175 +0x38
github.com/srl-labs/containerlab/cmd.destroyLab(...)
        github.com/srl-labs/containerlab/cmd/destroy.go:171
github.com/srl-labs/containerlab/cmd.destroyFn(0x4e844a0?, {0x2abe5fc?, 0x4?, 0x2abe600?})
        github.com/srl-labs/containerlab/cmd/destroy.go:149 +0x894
github.com/spf13/cobra.(*Command).execute(0x4e844a0, {0x50a0a20, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.1/command.go:985 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x4e85300)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x344
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/srl-labs/containerlab/cmd.Execute()
        github.com/srl-labs/containerlab/cmd/root.go:49 +0x24
main.main()
        github.com/srl-labs/containerlab/main.go:10 +0x1c
```

**Comment by hellt** [comment]
Oops. That's not cool. Thanks for filing this, will be fixed

What files do we have on rpi os that identify the os release?
