### ISSUE TITLE
not able to use clab gen command

### ISSUE THREAD

**Issue by ksator** [srl-labs/containerlab#439]
Hello

I am using clab with my own topo files, it works great (I can deploy, destroy, and so on) ... 
 
But I am not able to use the clab gen command to generate topo files.   

Examples (with or without the flag `--deploy` at the end):
```
containerlab generate --name test --nodes 4:ceos,2:ceos --image ceos:4.26.0.1F --node-prefix eos 
containerlab generate --name test --nodes 4:ceos --nodes 2:ceos --image ceos:4.26.0.1F --node-prefix eos 
containerlab generate --name test --kind ceos --image ceos:4.26.0.1F --nodes 4,2 --node-prefix eos 
```
```
$ docker images
REPOSITORY   TAG         IMAGE ID       CREATED      SIZE
ceos         4.26.0.1F   b5bae21b645f   2 days ago   1.67GB
ceos         4.25.0F     51cc58579039   5 days ago   1.64GB
```
```
$ bash -c "$(curl -sL https://get-clab.srlinux.dev)"
containerlab is already at latest (0.14.3) version
```
```
$ containerlab version

                           _                   _       _     
                 _        (_)                 | |     | |    
 ____ ___  ____ | |_  ____ _ ____   ____  ____| | ____| | _  
/ ___) _ \|  _ \|  _)/ _  | |  _ \ / _  )/ ___) |/ _  | || \ 
( (__| |_|| | | | |_( ( | | | | | ( (/ /| |   | ( ( | | |_) )
\____)___/|_| |_|\___)_||_|_|_| |_|\____)_|   |_|\_||_|____/ 

version: 0.14.3
 commit: 0a42cfe
   date: 2021-05-28T10:19:14Z
 source: https://github.com/srl-labs/containerlab 
```
```
$ sudo containerlab generate --name test --kind ceos --image ceos:4.26.0.1F --nodes 4,2 --node-prefix eos --debug
DEBU[0000] parsed licenses: map[]                       
DEBU[0000] parsed images: map[ceos:ceos:4.26.0.1F]      
DEBU[0000] parsed nodes definitions: [{numNodes:4 kind:ceos typ:} {numNodes:2 kind:ceos typ:}] 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xbf681b]

goroutine 1 [running]:
github.com/srl-labs/containerlab/cmd.generateTopologyConfig(0x7ffe1f22a832, 0x4, 0x0, 0x0, 0xdbdef1, 0x5, 0xdbdef1, 0x5, 0xc0005a0c30, 0xc0005a0b40, ...)
        /home/runner/work/containerlab/containerlab/cmd/generate.go:137 +0xbb
github.com/srl-labs/containerlab/cmd.glob..func6(0x13b2840, 0xc000130a50, 0x0, 0xb, 0x0, 0x0)
        /home/runner/work/containerlab/containerlab/cmd/generate.go:82 +0x3c8
github.com/spf13/cobra.(*Command).execute(0x13b2840, 0xc0001309a0, 0xb, 0xb, 0x13b2840, 0xc0001309a0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x13b0b60, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/srl-labs/containerlab/cmd.Execute()
        /home/runner/work/containerlab/containerlab/cmd/root.go:39 +0x2d
main.main()
        /home/runner/work/containerlab/containerlab/main.go:6 +0x25
```
Are you facing the same issue? Are my commands corrects? 
Many thanks in advance!

**Comment by ksator** [comment]
```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 io.containerd.runtime.v1.linux
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-144-generic
 Operating System: Ubuntu 18.04.4 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.66GiB
 Name: automation_2
 ID: ZHJA:DT3U:CVD4:PJKX:7KYL:675S:6OEE:7WGQ:ESTY:YWOS:VZNK:V2UL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by karimra** [comment]
Hi @ksator, seeing the same issue. 
A struct is not properly initialized, will push a small PR

**Comment by ksator** [comment]
Thanks @karimra !!

**Comment by hellt** [comment]
Thanks @ksator for finding this!
Kudos to @karimra for a quick fix

The new `0.14.4` release has been created with this fix incorporated, you can do`clab version upgrade` to get it.
@ksator Feel free to close this, after checking if it works in your env

**Comment by ksator** [comment]
It works in my env.  
Thank you @karimra @hellt  for the awesome support and the various tools you created and maintain.
